#SIMULAING AREA OF A CIRCLE WITH SIMULATION ---------------------------

#Monte Carlo ------------------------------
sim_circle<- function(){
  #set seed 
  set.seed(123)
  #set number of trials
  n<-10000
  #generate radius r on uniform 
  r<- runif(n,1,4 )
  #average area of circle of radius = r
  mean(pi*r^2)
}

sim_circle() #21.84337 

#Inverse CDF -------------------------------
sim_circle_2<- function(){
  #set seed 
  set.seed(123)
  #set number of trials
  n<-10000
  #generate uniform 
  u<- runif(n,0,1)
  #generated radii using inverse CDF 
  r<-(3*u+1)
  #average area of circle  from inverse CDF radii 
  mean(pi*r^2)
}

sim_circle_2() #21.84337 same as above so inverse method is consistent

#Creating a list of areas generated by Inverse Transform ------
sim_circle_plot<- function(){
  set.seed(123)
  n<-10000
  u<- runif(n,0,1)
  r<-(3*u+1)
  pi*r^2
}
areas<-sim_circle_plot()

#Plotting simulation vs theoretical ---------------
#histogram with density not frequency 
hist((areas), xlim = c(3.142,50.264), freq = FALSE)
#true density curve overlayed 
lines(density(areas), lwd = 2)